### ISSUE TITLE
memcache: unexpected line in get response: "ERROR\r\n"

### ISSUE THREAD

**Issue by silenceper** [bradfitz/gomemcache#37] opened 2015-08-22 17:05 UTC
set the data to memcache no error return,but get the key it return this 
"memcache: unexpected line in get response: "ERROR\r\n""

**Comment by bradfitz** [comment] 2015-08-22 19:13
Sorry, you're going to have to provide much more information. What server version? What's your code

**Comment by silenceper** [comment] 2015-08-23 14:51
i use like this:
go setCache(mem,ttl,key,value)//start goroutine
value=getCache(mem,key)

it works on my local environment, but it return error when i push to the production environment(high concurrence web app)

**Comment by bradfitz** [comment] 2015-08-23 15:06
What is key?

**Comment by silenceper** [comment] 2015-08-23 15:24
i print some log like this:
```
[CACHE] key=pet:username:uid:21327205, memcache: unexpected line in get response: "ERROR\r\n"key notFound
start:  set pet:username:uid:21327205 10 60 12
write value: [34 115 105 108 101 110 99 101 112 101 114 34]
```

**Comment by bradfitz** [comment] 2015-08-23 15:30
That's just a cache miss, probably because your code is doing a setCache cache in a goroutine and then you're trying to immediately read it, without synchronization to wait for it to be populated. (not sure why you'd do that anyway.)

I'm closing this until you provide a complete stand-alone reproduction demo, and also provide the server version.

I don't think there's actually a bug here.

**Closed by bradfitz** 2015-08-23 15:30 UTC

**Comment by silenceper** [comment] 2015-08-23 16:05
oh ,it my fault.
I found that memcache server not support gets commond.

**Comment by silenceper** [comment] 2015-11-23 10:57
My memcache server not support `gets` commond , so i add use `get` command to fix.

**Comment by clee01** [comment] 2019-11-10 17:08
> oh ,it my fault.
> I found that memcache server not support gets commond.

How'd u solved this?
